language: emacs-lisp
sudo: false
cache:
  - directories:
      - "$HOME/emacs/"
env:
  - EMACS_VERSION=25.1
before_install:
  - export PATH="$HOME/bin:$PATH"
  - wget 'https://raw.githubusercontent.com/flycheck/emacs-travis/master/emacs-travis.mk'
  - mkdir -p "$HOME/emacs/$EMACS_VERSION"
  - make -f emacs-travis.mk install_emacs
  - make -f emacs-travis.mk install_cask
install:
  - cask install
script:
  - cask build
